shared_controllers:
    resource:
        path: ../src/Shared/Application/Controller/
        namespace: App\Shared\Application\Controller
    type: attribute
mod_controllers:
    resource:
        path: ../src/Mod/Application/Controller/
        namespace: App\Mod\Application\Controller
    type: attribute
