parameters:
    file_upload_path: "%kernel.project_dir%/var/uploads/"
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: ../src/
        exclude:
            - ../src/DependencyInjection/
            - ../src/Shared/Infrastructure/Symfony/Kernel.php
            - ../src/Shared/Infrastructure/Doctrine/Migration/
            - ../src/Shared/Infrastructure/Symfony/Command/templates/
            - "%kernel.project_dir%/src/Shared/Domain/Entity/"
            - "%kernel.project_dir%/src/Mod/Domain/Entity/"
