parameters:
    filesystem_type: "local" # or 's3'
    filesystem_config.path: "%kernel.project_dir%/var/uploads"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Infrastructure/Symfony/Kernel.php"
            - "../src/Infrastructure/Doctrine/Migration/"
            - "%kernel.project_dir%/src/Domain/Entity/"

    App\Infrastructure\Exception\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
        arguments:
            $logger: "@logger"
            $environment: "%kernel.environment%"

    App\Infrastructure\FileSystem\FileSystemFactory:
        arguments:
            $type: "%filesystem_type%"
            $config: "%filesystem_config%"

    App\Infrastructure\FileSystem\LocalFileSystem:
        arguments:
            $path: "%filesystem_config.path%"

    App\Infrastructure\Doctrine\Listener\DoctrineFileDeletionListener:
        arguments:
            $fileSystem: '@App\Domain\FileSystem\FileSystemInterface'
        tags:
            - { name: doctrine.event_listener, event: preRemove }
